### ISSUE TITLE
BrAPI

### ISSUE THREAD

**Issue by fogliafabrizio** [germinateplatform/germinate-vue#20]
good evening,

I saw the BrAPI documentation and wanted to ask for some information.

First, I would like to know how I can connect to my server and then make the calls.
I saw that API requests are structured as
    https: // <server> / brapi / v2 / <call>
but i can't figure out what to put in the server.

Subsequently, I read that one of the possible calls concerns Crossing Projects; I wanted to know if they are present in Germinate and, therefore, are usable.

If there are no Crossing Projects, would it be possible to modify the database locally?

For example, would it be possible to add a column to one of the tables on Germinate?

Finally, I would like to ask for some clarification on BrAPI calls:

- among all the possible calls, how can I know which ones can be performed on Germinate?
- why (taking as an example the call to create a new Germplasm) is there a difference between the fields required by the Excel templates and the fields required by the BrAPI call?

Thank you in advance and wish you a good day.

Foglia Fabrizio

**Comment by fogliafabrizio** [comment]
Good Evening

Since the crossing projects are not present, we are thinking about creating our own version starting from the current version of Germinate.
Beyond that, we were planning to develop new features to add.
I wanted to ask if you were interested in introducing these features and, if so, send a Pull Request to the repo to validate what we will do and possibly include the new feature in the official version.

Foglia Fabrizio

**Comment by sebastian-raubach** [comment]
We're open to contributions in general. Before you go and do any work, it may be a good to run your ideas past us to make sure they align with the database structure and our goals. Feel free to get in touch via germinate@hutton.ac.uk to discuss this outside of this issue.

**Comment by fogliafabrizio** [comment]
Thank you very much, I just wrote an email to germinate@hutton.ac.uk where I explained all the necessary points.
