### ISSUE TITLE
How to insert data?

### ISSUE THREAD

**Issue by brunopnogueira92** [germinateplatform/germinate-vue#3]
Thank you in advance for your time.

I'm trying out your application to integrate into a biology project that I have.
I've already managed locally using your tutorial to get the application running, but I didn't understand how I input my data into the platform.

Can you help me?

**Comment by sebastian-raubach** [comment]
There are a few ways to get your data into Germinate.
The preferred option is to use the [Germinate data templates](https://github.com/germinateplatform/germinate-data-templates). These are Excel spreadsheets for the main data types within Germinate. These can be imported into the database by either using a commandline tool or the Germinate web interface. Documentation on how to do this is still missing and needs to be written. Using the Germinate interface requires that you use Gatekeeper for user authentication, as we're only allowing data curators to add data into the database.
Another option for users with thorough understanding of the database design is to directly interact with the database using tools like DBeaver or Navicat, or using something like [Germinate Daim](https://github.com/germinateplatform/germinate-daim), but this is probably not the option you'd want to start with.

I'd recommend looking into the data templates and trying to fit your data into the Excel files. There's documentation on how to do this and example files available in the GitHub repo.
I'll hopefully get a chance to write documentation about how to import the data templates into the database soon.

**Comment by brunopnogueira92** [comment]
Thanks for the answers.

By the way, I read somewhere that Germinate can integrate with BRAPI.How do you integrate with BRAPI?

Do I have to integrate Geetkeeper to enter the data via Germinate client?

**Comment by sebastian-raubach** [comment]
BrAPI support us currently under development for the new release of Germinate. It'll be a while before it's production ready.

What do you mean when you say "Germinate client"? The web interface? Then yes, you do need Gatekeeper if you want to upload the templates via the web interface.

**Comment by brunopnogueira92** [comment]
> BrAPI support us currently under development for the new release of Germinate. It'll be a while before it's production ready.
> 
> What do you mean when you say "Germinate client"? The web interface? Then yes, you do need Gatekeeper if you want to upload the templates via the web interface.

Thanks for the explanation.

Sorry to ask, but how do I install the gatekeeper-vue and the gatekeeper-server? Is there a procedure for the installation?

**Comment by sebastian-raubach** [comment]
The process is pretty identical to Germinate. There are instructions here: https://germinateplatform.github.io/gatekeeper-server/

**Comment by brunopnogueira92** [comment]
Thank you so much for your help.

I wasn't finding the website you indicated.
If you don't mind me saying, it'd be nice to stick that url in the github repository. 

I'll try it and if you have any more questions I'll write.

Thanks again.
