### ISSUE TITLE
Automatic Logout After  'Submit' button Pressed in Germinate Settings page

### ISSUE THREAD

**Issue by illxi** [germinateplatform/germinate-vue#33]
Whenever I press the 'Submit' button on the Germinate Settings page, I am automatically logged out. However, the changes I made are saved.

**Comment by sebastian-raubach** [comment]
Yes, that's currently the expected behaviour, because the changes you may have made could affect Germinate's authentication settings or the Gatekeeper connection settings after which a re-login is required.
